package gg.warcraft.monolith.spigot.effect

import gg.warcraft.monolith.api.effect.Particle
import org.bukkit.{Color => SpigotColor, Particle => SpigotParticle}

class SpigotParticleMapper {
  def map(particle: SpigotParticle): Particle = particle match {
    case SpigotParticle.BARRIER               => Particle.Barrier
    case SpigotParticle.BLOCK_CRACK           => Particle.BlockCrack
    case SpigotParticle.BLOCK_DUST            => Particle.BlockDust
    case SpigotParticle.BUBBLE_COLUMN_UP      => Particle.BubbleColumnUp
    case SpigotParticle.BUBBLE_POP            => Particle.BubblePop
    case SpigotParticle.CAMPFIRE_COSY_SMOKE   => Particle.CampfireCosySmoke
    case SpigotParticle.CAMPFIRE_SIGNAL_SMOKE => Particle.CampfireSignalSmoke
    case SpigotParticle.CLOUD                 => Particle.Cloud
    case SpigotParticle.COMPOSTER             => Particle.Composter
    case SpigotParticle.CRIT                  => Particle.Crit
    case SpigotParticle.CRIT_MAGIC            => Particle.CritMagic
    case SpigotParticle.CURRENT_DOWN          => Particle.CurrentDown
    case SpigotParticle.DAMAGE_INDICATOR      => Particle.DamageIndicator
    case SpigotParticle.DOLPHIN               => Particle.Dolphin
    case SpigotParticle.DRAGON_BREATH         => Particle.DragonBreath
    case SpigotParticle.DRIPPING_HONEY        => Particle.DrippingHoney
    case SpigotParticle.DRIP_LAVA             => Particle.DripLava
    case SpigotParticle.DRIP_WATER            => Particle.DripWater
    case SpigotParticle.ENCHANTMENT_TABLE     => Particle.EnchantmentTable
    case SpigotParticle.END_ROD               => Particle.EndRod
    case SpigotParticle.EXPLOSION_HUGE        => Particle.ExplosionHuge
    case SpigotParticle.EXPLOSION_LARGE       => Particle.ExplosionLarge
    case SpigotParticle.EXPLOSION_NORMAL      => Particle.ExplosionNormal
    case SpigotParticle.FALLING_DUST          => Particle.FallingDust
    case SpigotParticle.FALLING_HONEY         => Particle.FallingHoney
    case SpigotParticle.FALLING_LAVA          => Particle.FallingLava
    case SpigotParticle.FALLING_NECTAR        => Particle.FallingNectar
    case SpigotParticle.FALLING_WATER         => Particle.FallingWater
    case SpigotParticle.FIREWORKS_SPARK       => Particle.FireworksSpark
    case SpigotParticle.FLAME                 => Particle.Flame
    case SpigotParticle.FLASH                 => Particle.Flash
    case SpigotParticle.HEART                 => Particle.Heart
    case SpigotParticle.ITEM_CRACK            => Particle.ItemCrack
    case SpigotParticle.LANDING_HONEY         => Particle.LandingHoney
    case SpigotParticle.LANDING_LAVA          => Particle.LandingLava
    case SpigotParticle.LAVA                  => Particle.Lava
    case SpigotParticle.LEGACY_BLOCK_CRACK    => Particle.LegacyBlockCrack
    case SpigotParticle.LEGACY_BLOCK_DUST     => Particle.LegacyBlockDust
    case SpigotParticle.LEGACY_FALLING_DUST   => Particle.LegacyFallingDust
    case SpigotParticle.MOB_APPEARANCE        => Particle.MobAppearance
    case SpigotParticle.NAUTILUS              => Particle.Nautilus
    case SpigotParticle.NOTE                  => Particle.Note
    case SpigotParticle.PORTAL                => Particle.Portal
    case SpigotParticle.REDSTONE              => Particle.Redstone
    case SpigotParticle.SLIME                 => Particle.Slime
    case SpigotParticle.SMOKE_LARGE           => Particle.SmokeLarge
    case SpigotParticle.SMOKE_NORMAL          => Particle.SmokeNormal
    case SpigotParticle.SNEEZE                => Particle.Sneeze
    case SpigotParticle.SNOWBALL              => Particle.Snowball
    case SpigotParticle.SNOW_SHOVEL           => Particle.SnowShovel
    case SpigotParticle.SPELL                 => Particle.Spell
    case SpigotParticle.SPELL_INSTANT         => Particle.SpellInstant
    case SpigotParticle.SPELL_MOB             => Particle.SpellMob
    case SpigotParticle.SPELL_MOB_AMBIENT     => Particle.SpellMobAmbient
    case SpigotParticle.SPELL_WITCH           => Particle.SpellWitch
    case SpigotParticle.SPIT                  => Particle.Spit
    case SpigotParticle.SQUID_INK             => Particle.SquidInk
    case SpigotParticle.SUSPENDED             => Particle.Suspended
    case SpigotParticle.SUSPENDED_DEPTH       => Particle.SuspendedDepth
    case SpigotParticle.SWEEP_ATTACK          => Particle.SweepAttack
    case SpigotParticle.TOTEM                 => Particle.Totem
    case SpigotParticle.TOWN_AURA             => Particle.TownAura
    case SpigotParticle.VILLAGER_ANGRY        => Particle.VillagerAngry
    case SpigotParticle.VILLAGER_HAPPY        => Particle.VillagerHappy
    case SpigotParticle.WATER_BUBBLE          => Particle.WaterBubble
    case SpigotParticle.WATER_DROP            => Particle.WaterDrop
    case SpigotParticle.WATER_SPLASH          => Particle.WaterSplash
    case SpigotParticle.WATER_WAKE            => Particle.WaterWake
  }

  def map(particle: Particle): SpigotParticle = particle match {
    case Particle.Barrier             => SpigotParticle.BARRIER
    case Particle.BlockCrack          => SpigotParticle.BLOCK_CRACK
    case Particle.BlockDust           => SpigotParticle.BLOCK_DUST
    case Particle.BubbleColumnUp      => SpigotParticle.BUBBLE_COLUMN_UP
    case Particle.BubblePop           => SpigotParticle.BUBBLE_POP
    case Particle.CampfireCosySmoke   => SpigotParticle.CAMPFIRE_COSY_SMOKE
    case Particle.CampfireSignalSmoke => SpigotParticle.CAMPFIRE_SIGNAL_SMOKE
    case Particle.Cloud               => SpigotParticle.CLOUD
    case Particle.Composter           => SpigotParticle.COMPOSTER
    case Particle.Crit                => SpigotParticle.CRIT
    case Particle.CritMagic           => SpigotParticle.CRIT_MAGIC
    case Particle.CurrentDown         => SpigotParticle.CURRENT_DOWN
    case Particle.DamageIndicator     => SpigotParticle.DAMAGE_INDICATOR
    case Particle.Dolphin             => SpigotParticle.DOLPHIN
    case Particle.DragonBreath        => SpigotParticle.DRAGON_BREATH
    case Particle.DripLava            => SpigotParticle.DRIPPING_HONEY
    case Particle.DripWater           => SpigotParticle.DRIP_LAVA
    case Particle.DrippingHoney       => SpigotParticle.DRIP_WATER
    case Particle.EnchantmentTable    => SpigotParticle.ENCHANTMENT_TABLE
    case Particle.EndRod              => SpigotParticle.END_ROD
    case Particle.ExplosionHuge       => SpigotParticle.EXPLOSION_HUGE
    case Particle.ExplosionLarge      => SpigotParticle.EXPLOSION_LARGE
    case Particle.ExplosionNormal     => SpigotParticle.EXPLOSION_NORMAL
    case Particle.FallingDust         => SpigotParticle.FALLING_DUST
    case Particle.FallingHoney        => SpigotParticle.FALLING_HONEY
    case Particle.FallingLava         => SpigotParticle.FALLING_LAVA
    case Particle.FallingNectar       => SpigotParticle.FALLING_NECTAR
    case Particle.FallingWater        => SpigotParticle.FALLING_WATER
    case Particle.FireworksSpark      => SpigotParticle.FIREWORKS_SPARK
    case Particle.Flame               => SpigotParticle.FLAME
    case Particle.Flash               => SpigotParticle.FLASH
    case Particle.Heart               => SpigotParticle.HEART
    case Particle.ItemCrack           => SpigotParticle.ITEM_CRACK
    case Particle.LandingHoney        => SpigotParticle.LANDING_HONEY
    case Particle.LandingLava         => SpigotParticle.LANDING_LAVA
    case Particle.Lava                => SpigotParticle.LAVA
    case Particle.LegacyBlockCrack    => SpigotParticle.LEGACY_BLOCK_CRACK
    case Particle.LegacyBlockDust     => SpigotParticle.LEGACY_BLOCK_DUST
    case Particle.LegacyFallingDust   => SpigotParticle.LEGACY_FALLING_DUST
    case Particle.MobAppearance       => SpigotParticle.MOB_APPEARANCE
    case Particle.Nautilus            => SpigotParticle.NAUTILUS
    case Particle.Note                => SpigotParticle.NOTE
    case Particle.Portal              => SpigotParticle.PORTAL
    case Particle.Redstone            => SpigotParticle.REDSTONE
    case Particle.Slime               => SpigotParticle.SLIME
    case Particle.SmokeLarge          => SpigotParticle.SMOKE_LARGE
    case Particle.SmokeNormal         => SpigotParticle.SMOKE_NORMAL
    case Particle.Sneeze              => SpigotParticle.SNEEZE
    case Particle.SnowShovel          => SpigotParticle.SNOWBALL
    case Particle.Snowball            => SpigotParticle.SNOW_SHOVEL
    case Particle.Spell               => SpigotParticle.SPELL
    case Particle.SpellInstant        => SpigotParticle.SPELL_INSTANT
    case Particle.SpellMob            => SpigotParticle.SPELL_MOB
    case Particle.SpellMobAmbient     => SpigotParticle.SPELL_MOB_AMBIENT
    case Particle.SpellWitch          => SpigotParticle.SPELL_WITCH
    case Particle.Spit                => SpigotParticle.SPIT
    case Particle.SquidInk            => SpigotParticle.SQUID_INK
    case Particle.Suspended           => SpigotParticle.SUSPENDED
    case Particle.SuspendedDepth      => SpigotParticle.SUSPENDED_DEPTH
    case Particle.SweepAttack         => SpigotParticle.SWEEP_ATTACK
    case Particle.Totem               => SpigotParticle.TOTEM
    case Particle.TownAura            => SpigotParticle.TOWN_AURA
    case Particle.VillagerAngry       => SpigotParticle.VILLAGER_ANGRY
    case Particle.VillagerHappy       => SpigotParticle.VILLAGER_HAPPY
    case Particle.WaterBubble         => SpigotParticle.WATER_BUBBLE
    case Particle.WaterDrop           => SpigotParticle.WATER_DROP
    case Particle.WaterSplash         => SpigotParticle.WATER_SPLASH
    case Particle.WaterWake           => SpigotParticle.WATER_WAKE
  }

  def map(color: SpigotColor): Particle.Color = color match {
    case _ => ???
  }

  def map(color: Particle.Color): SpigotColor = color match {
    case Particle.Color.Aqua    => ???
    case Particle.Color.Black   => ???
    case Particle.Color.Blue    => ???
    case Particle.Color.Fuchsia => ???
    case Particle.Color.Gray    => ???
    case Particle.Color.Green   => ???
    case Particle.Color.Lime    => ???
    case Particle.Color.Maroon  => ???
    case Particle.Color.Navy    => ???
    case Particle.Color.Olive   => ???
    case Particle.Color.Orange  => ???
    case Particle.Color.Purple  => ???
    case Particle.Color.Red     => ???
    case Particle.Color.Silver  => ???
    case Particle.Color.Teal    => ???
    case Particle.Color.White   => ???
    case Particle.Color.Yellow  => ???
  }
}
