package gg.warcraft.monolith.api.world.item;

public enum ItemAttribute {
    ENTITY_MAX_HEALTH,
    ENTITY_FOLLOW_RANGE,
    ENTITY_KNOCKBACK_RESISTANCE,
    ENTITY_MOVEMENT_SPEED,
    ENTITY_ATTACK_DAMAGE,
    ENTITY_ARMOR,
    ENTITY_ARMOR_TOUGHNESS,

    HORSE_JUMP_STRENGTH,

    PARROT_FLYING_SPEED,

    PLAYER_ATTACK_SPEED,
    PLAYER_LUCK,

    ZOMBIE_SPAWN_REINFORCEMENTS,
}
