package gg.warcraft.monolith.spigot.world.item;

import gg.warcraft.monolith.api.world.item.ItemType;
import org.bukkit.Material;

public class JSpigotItemTypeMapper extends SpigotItemTypeMapper {
    @Override
    public Material map(ItemType type) {
        switch (type) {
            case BOTTLE_OF_ENCHANTING:
                return Material.EXPERIENCE_BOTTLE;
            case BRICK_BLOCK:
                return Material.BRICKS;
            case CLAY:
                return Material.CLAY_BALL;
            case CLAY_BLOCK:
                return Material.CLAY;
            case GOLDEN_MELON_SLICE:
                return Material.GLISTERING_MELON_SLICE;
            case HAY_BALE:
                return Material.HAY_BLOCK;
            case INFESTED_BLOCK:
                return Material.INFESTED_STONE;
            case JACK_OF_THE_LANTERN:
                return Material.JACK_O_LANTERN;
            case JIGSAW_BLOCK:
                return Material.JIGSAW;
            case LAPIS:
                return Material.LAPIS_LAZULI;
            case QUARTZ_ORE:
                return Material.NETHER_QUARTZ_ORE;
            case SLIMEBALL:
                return Material.SLIME_BALL;
            case BOOK_AND_QUILL:
                return Material.WRITABLE_BOOK;

            // variable items with no clear default
            case AXE:
                return Material.WOODEN_AXE;
            case BANNER:
                return Material.RED_BANNER;
            case BANNER_PATTERN:
                return Material.CREEPER_BANNER_PATTERN;
            case BED:
                return Material.RED_BED;
            case BOAT:
                return Material.OAK_BOAT;
            case BOOTS:
                return Material.LEATHER_BOOTS;
            case BUTTON:
                return Material.OAK_BUTTON;
            case CARPET:
                return Material.RED_CARPET;
            case CHESTPLATE:
                return Material.LEATHER_CHESTPLATE;
            case CONCRETE:
                return Material.RED_CONCRETE;
            case CONCRETE_POWDER:
                return Material.RED_CONCRETE_POWDER;
            case CORAL:
                return Material.BRAIN_CORAL;
            case CORAL_BLOCK:
                return Material.BRAIN_CORAL_BLOCK;
            case CORAL_FAN:
                return Material.BRAIN_CORAL_FAN;
            case DOOR:
                return Material.OAK_DOOR;
            case DYE:
                return Material.RED_DYE;
            case FENCE:
                return Material.OAK_FENCE;
            case FLOWER:
                return Material.POPPY;
            case FENCE_GATE:
                return Material.OAK_FENCE_GATE;
            case GLAZED_TERRACOTTA:
                return Material.RED_GLAZED_TERRACOTTA;
            case HELMET:
                return Material.LEATHER_HELMET;
            case HOE:
                return Material.WOODEN_HOE;
            case HORSE_ARMOR:
                return Material.LEATHER_HORSE_ARMOR;
            case LEAVES:
                return Material.OAK_LEAVES;
            case LEGGINGS:
                return Material.LEATHER_LEGGINGS;
            case LOG:
                return Material.OAK_LOG;
            case MOB_HEAD:
                return Material.CREEPER_HEAD;
            case MUSHROOM:
                return Material.RED_MUSHROOM;
            case MUSHROOM_BLOCK:
                return Material.RED_MUSHROOM_BLOCK;
            case MUSIC_DISC:
                return Material.MUSIC_DISC_CAT;
            case PICKAXE:
                return Material.WOODEN_PICKAXE;
            case PILLAR:
                return Material.QUARTZ_PILLAR;
            case PLANKS:
                return Material.OAK_PLANKS;
            case PLANT:
                return Material.LILAC;
            case PRESSURE_PLATE:
                return Material.OAK_PRESSURE_PLATE;
            case SAPLING:
                return Material.OAK_SAPLING;
            case SEEDS:
                return Material.WHEAT_SEEDS;
            case SHOVEL:
                return Material.WOODEN_SHOVEL;
            case SIGN:
                return Material.OAK_SIGN;
            case SLAB:
                return Material.OAK_SLAB;
            case SPAWN_EGG:
                return Material.CAT_SPAWN_EGG;
            case STAIRS:
                return Material.OAK_STAIRS;
            case STEW:
                return Material.MUSHROOM_STEW;
            case SWORD:
                return Material.WOODEN_SWORD;
            case TRAPDOOR:
                return Material.OAK_TRAPDOOR;
            case WALL:
                return Material.COBBLESTONE_WALL;
            case WEIGHTED_PRESSURE_PLATE:
                return Material.LIGHT_WEIGHTED_PRESSURE_PLATE;
            case WOOD:
                return Material.OAK_WOOD;
            case WOOL:
                return Material.RED_WOOL;

            default:
                return Material.valueOf(type.name());
        }
    }
}
