buildRepository:
  boundingBox:
    world: world
    min: { x: 0, y: 0, z: 0 }
    max: { x: 0, y: 0, z: 0 }
  orientation: NORTH

database:
  # if embedded is set to yes the plugin will create an H2 database
  # in the plugin data folder and doesn't require any other setup.
  embedded: yes
  # if embedded is set to no the plugin will attempt to connect to a
  # hosted database using any of the following settings:
  postgres: ~
#    host: localhost
#    port: 5432
#    database: postgres
#    user: postgres
#    password: postgres
#    ssl: yes

maintenanceMode:
  active: no
  permission: monolith.staff

teams: []

# Staff Permissions
staffPermission: monolith.staff
modPermission: monolith.mod
adminPermission: monolith.admin
devPermission: monolith.dev

# Miscellaneous
baseHealth: 20
serverTimeZoneUtcOffset: "Z"
shutdownMessage: The server is going down for maintenance.

tipsPeriodInMinutes: 10
tips:
  - Any feedback? Please let us know at discord.link.here!
