name: Monolith
version: 20.2.0-SNAPSHOT
api-version: 1.20

author: fishb6nes
website: http://warcraft.gg

main: gg.warcraft.monolith.spigot.MonolithPlugin
softdepend: [ Multiverse-Core ]
loadbefore: [ EssentialsX ]
