name: "Monolith"
version: "16.0.0-SNAPSHOT"
api-version: "1.16"

author: fishb6nes
website: http://warcraft.gg

main: gg.warcraft.monolith.spigot.MonolithPlugin
softdepend: [ Multiverse-Core ]
loadbefore: [ EssentialsX ]
