name: "Monolith"
version: "15.0.0-SNAPSHOT"
api-version: "1.15"

author: fishb6nes
website: http://warcraft.gg

main: gg.warcraft.monolith.spigot.MonolithPlugin
load: STARTUP
softdepend: [ Multiverse-Core ]
loadbefore: [ EssentialsX ]
