/*
 * MIT License
 *
 * Copyright (c) 2020 WarCraft <https://github.com/WarCraft>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package gg.warcraft.monolith.api.block;

public enum BlockType implements BlockTypeVariantOrState {
    AIR,
    ANDESITE,
    ANVIL,
    BAMBOO,
    BANNER,
    BARREL,
    BARRIER,
    BEACON,
    BED,
    BEDROCK,
    BEE_NEST,
    BEEHIVE,
    BEETROOTS,
    BELL,
    BLAST_FURNACE,
    BONE_BLOCK,
    BOOKSHELF,
    BREWING_STAND,
    BRICK_BLOCK,
    BUBBLE_COLUMN,
    BUTTON,
    CACTUS,
    CAKE,
    CAMPFIRE,
    CARPET,
    CARROTS,
    CARTOGRAPHY_TABLE,
    CAULDRON,
    CHEST,
    CHORUS_FLOWER,
    CHORUS_PLANT,
    CLAY_BLOCK,
    COAL_BLOCK,
    COAL_ORE,
    COBBLESTONE,
    COBWEB,
    COCOA_POD,
    COMMAND_BLOCK,
    COMPARATOR,
    COMPOSTER,
    CONCRETE,
    CONCRETE_POWDER,
    CONDUIT,
    CORAL,
    CORAL_BLOCK,
    CORAL_FAN,
    CRAFTING_TABLE,
    DAYLIGHT_DETECTOR,
    DEAD_BUSH,
    DIAMOND_BLOCK,
    DIAMOND_ORE,
    DIORITE,
    DIRT,
    DISPENSER,
    DOOR,
    DRAGON_EGG,
    DRIED_KELP_BLOCK,
    DROPPER,
    EMERALD_BLOCK,
    EMERALD_ORE,
    ENCHANTING_TABLE,
    END_GATEWAY,
    END_PORTAL,
    END_PORTAL_FRAME,
    END_ROD,
    END_STONE,
    END_STONE_BRICK,
    FARMLAND,
    FENCE,
    FERN,
    FIRE,
    FLETCHING_TABLE,
    FLOWER,
    FLOWER_POT,
    FROST,
    FURNACE,
    FENCE_GATE,
    GLASS,
    GLASS_PANE,
    GLAZED_TERRACOTTA,
    GLOWSTONE,
    GOLD_BLOCK,
    GOLD_ORE,
    GRANITE,
    GRASS,
    GRASS_BLOCK,
    GRASS_PATH,
    GRAVEL,
    GRINDSTONE,
    HARDENED_CLAY,
    HAY_BALE,
    HONEY_BLOCK,
    HONEYCOMB_BLOCK,
    HOPPER,
    ICE,
    INFESTED_BLOCK,
    IRON_BLOCK,
    IRON_BARS,
    IRON_ORE,
    JIGSAW_BLOCK,
    JUKEBOX,
    KELP,
    LADDER,
    LANTERN,
    LAPIS_BLOCK,
    LAPIS_ORE,
    LAVA,
    LEAVES,
    LECTERN,
    LEVER,
    LILY_PAD,
    LOG,
    LOOM,
    MAGMA_BLOCK,
    MELON,
    MELON_STEM,
    MINERAL,
    MOB_HEAD,
    MUSHROOM,
    MUSHROOM_BLOCK,
    MYCELIUM,
    NETHERRACK,
    NETHER_PORTAL,
    NETHER_WARTS,
    NETHER_WART_BLOCK,
    NOTE_BLOCK,
    OBSERVER,
    OBSIDIAN,
    ORE,
    PLANKS,
    PLANT,
    PILLAR,
    PISTON,
    PISTON_HEAD,
    PODZOL,
    POTATOES,
    PRESSURE_PLATE,
    PRISMARINE,
    PUMPKIN,
    PUMPKIN_STEM,
    PURPUR_BLOCK,
    QUARTZ_BLOCK,
    QUARTZ_ORE,
    RAIL,
    REDSTONE_BLOCK,
    REDSTONE_LAMP,
    REDSTONE_ORE,
    REDSTONE_TORCH,
    REDSTONE_WIRE,
    REPEATER,
    SAND,
    SANDSTONE,
    SAPLING,
    SCAFFOLDING,
    SEAGRASS,
    SEA_LANTERN,
    SEA_PICKLE,
    SHULKER_BOX,
    SIGN,
    SLAB,
    SLIME_BLOCK,
    SMITHING_TABLE,
    SMOKER,
    SNOW,
    SNOW_BLOCK,
    SOUL_SAND,
    SPAWNER,
    SPONGE,
    STAIRS,
    STONE,
    STONE_BRICK,
    STONECUTTER,
    STRUCTURE_BLOCK,
    SUGAR_CANE,
    SWEET_BERRY_BUSH,
    TERRACOTTA,
    TNT,
    TORCH,
    TRAPDOOR,
    TRIPWIRE,
    TRIPWIRE_HOOK,
    TURTLE_EGG,
    VINES,
    WALL,
    WATER,
    WEIGHTED_PRESSURE_PLATE,
    WHEAT,
    WOOD,
    WOOL,
}
